// Generated by GitHub Copilot
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcrypt');

const prisma = new PrismaClient();
const SALT_ROUNDS = 12;

async function main() {
  try {
    console.log('Starting seed...');

    const adminPassword = await bcrypt.hash('Admin@123', SALT_ROUNDS);
    const employeePassword = await bcrypt.hash('Employee@123', SALT_ROUNDS);

    const adminUser = await prisma.user.upsert({
      where: { email: 'admin@bookhive.com' },
      update: {},
      create: {
        email: 'admin@bookhive.com',
        password: adminPassword,
        name: 'Admin User',
        role: 'ADMIN'
      }
    });

    console.log('Admin user ready:', adminUser.email);

    const employeeUser = await prisma.user.upsert({
      where: { email: 'employee@bookhive.com' },
      update: {},
      create: {
        email: 'employee@bookhive.com',
        password: employeePassword,
        name: 'Employee User',
        role: 'EMPLOYEE'
      }
    });

    console.log('Employee user ready:', employeeUser.email);
    console.log('Credentials: admin@bookhive.com / Admin@123');
    console.log('Credentials: employee@bookhive.com / Employee@123');
  } catch (error) {
    console.error('Seed failed:', error);
    process.exitCode = 1;
  } finally {
    await prisma.$disconnect();
  }
}

main();