// Generated by GitHub Copilot
import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcrypt';

const prisma = new PrismaClient();

const SALT_ROUNDS = 12;

async function main() {
  try {
    console.log('🌱 Starting seed...');

    // Hash passwords
    const adminPassword = await bcrypt.hash('Admin@123', SALT_ROUNDS);
    const employeePassword = await bcrypt.hash('Employee@123', SALT_ROUNDS);

    // Create admin user
    const adminUser = await prisma.user.upsert({
      where: { email: 'admin@bookhive.com' },
      update: {},
      create: {
        email: 'admin@bookhive.com',
        password: adminPassword,
        name: 'Admin User',
        role: 'ADMIN'
      }
    });

    console.log('✅ Admin user created:', adminUser);

    // Create employee user
    const employeeUser = await prisma.user.upsert({
      where: { email: 'employee@bookhive.com' },
      update: {},
      create: {
        email: 'employee@bookhive.com',
        password: employeePassword,
        name: 'Employee User',
        role: 'EMPLOYEE'
      }
    });

    console.log('✅ Employee user created:', employeeUser);

    console.log('\n📋 Credentials:');
    console.log('Admin: admin@bookhive.com / Admin@123');
    console.log('Employee: employee@bookhive.com / Employee@123');
  } catch (error) {
    console.error('❌ Seed error:', error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}

main();
