// Generated by GitHub Copilot
import { spawn } from 'node:child_process';
import { randomBytes } from 'node:crypto';
import { promises as fs } from 'node:fs';
import path from 'node:path';
import process from 'node:process';
import { fileURLToPath } from 'node:url';

const rootDir = path.dirname(fileURLToPath(import.meta.url));
const backendDir = path.join(rootDir, 'backend');
const frontendDir = path.join(rootDir, 'frontend');
const backendEnvPath = path.join(backendDir, '.env');
const backendNodeModules = path.join(backendDir, 'node_modules');
const frontendNodeModules = path.join(frontendDir, 'node_modules');
const checkOnly = process.argv.includes('--check');

const children = [];
let shuttingDown = false;

function randomSecret() {
  return randomBytes(32).toString('hex');
}

async function pathExists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

function log(section, message) {
  process.stdout.write(`[${section}] ${message}\n`);
}

function spawnWithPrefix(label, command, args, cwd) {
  const child = spawn(command, args, {
    cwd,
    env: process.env,
    shell: process.platform === 'win32',
    stdio: ['ignore', 'pipe', 'pipe']
  });

  children.push(child);

  let stdoutBuffer = '';
  let stderrBuffer = '';

  const writeChunk = (bufferRef, chunk, stream) => {
    const nextBuffer = `${bufferRef}${chunk.toString()}`;
    const lines = nextBuffer.split(/\r?\n/);
    const remainder = lines.pop() ?? '';

    for (const line of lines) {
      if (line.length > 0) {
        stream.write(`[${label}] ${line}\n`);
      }
    }

    return remainder;
  };

  child.stdout?.on('data', (chunk) => {
    stdoutBuffer = writeChunk(stdoutBuffer, chunk, process.stdout);
  });

  child.stderr?.on('data', (chunk) => {
    stderrBuffer = writeChunk(stderrBuffer, chunk, process.stderr);
  });

  child.on('close', (code, signal) => {
    if (stdoutBuffer.length > 0) {
      process.stdout.write(`[${label}] ${stdoutBuffer}\n`);
      stdoutBuffer = '';
    }

    if (stderrBuffer.length > 0) {
      process.stderr.write(`[${label}] ${stderrBuffer}\n`);
      stderrBuffer = '';
    }

    const exitLabel = signal ? `signal ${signal}` : `code ${code ?? 0}`;
    log(label, `exited with ${exitLabel}`);

    if (!shuttingDown && (code ?? 0) !== 0) {
      void shutdown(code ?? 1);
    }
  });

  return child;
}

async function runCommand(command, args, cwd) {
  log('SETUP', `${command} ${args.join(' ')} (${path.relative(rootDir, cwd)})`);

  await new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd,
      env: process.env,
      shell: process.platform === 'win32',
      stdio: 'inherit'
    });

    child.on('error', reject);
    child.on('exit', (code, signal) => {
      if (signal) {
        reject(new Error(`${command} terminated with ${signal}`));
        return;
      }

      if ((code ?? 0) !== 0) {
        reject(new Error(`${command} exited with code ${code}`));
        return;
      }

      resolve(undefined);
    });
  });
}

async function ensureLocalEnv() {
  if (await pathExists(backendEnvPath)) {
    return;
  }

  const localEnv = [
    'NODE_ENV=development',
    'PORT=4000',
    'API_PREFIX=/api',
    'API_VERSION=v1',
    'DATABASE_URL="file:./prisma/dev.db"',
    `JWT_ACCESS_SECRET=${randomSecret()}`,
    'JWT_ACCESS_EXPIRES_IN=15m',
    `JWT_REFRESH_SECRET=${randomSecret()}`,
    'JWT_REFRESH_EXPIRES_IN=7d',
    'LOG_LEVEL=info',
    'CORS_ORIGIN=http://localhost:5173,http://127.0.0.1:5173,http://localhost:5174,http://127.0.0.1:5174,http://localhost:5175,http://127.0.0.1:5175,http://localhost:5176,http://127.0.0.1:5176,http://localhost:5177,http://127.0.0.1:5177',
    'AI_PROVIDER=github',
    ''
  ].join('\n');

  await fs.writeFile(backendEnvPath, localEnv, 'utf8');
  log('SETUP', 'Created backend/.env for local SQLite development');
}

async function ensureDependencies() {
  if (!(await pathExists(backendNodeModules))) {
    const backendLockfile = await pathExists(path.join(backendDir, 'package-lock.json'));
    await runCommand('npm', backendLockfile ? ['ci'] : ['install'], backendDir);
  }

  if (!(await pathExists(frontendNodeModules))) {
    const frontendLockfile = await pathExists(path.join(frontendDir, 'package-lock.json'));
    await runCommand('npm', frontendLockfile ? ['ci'] : ['install'], frontendDir);
  }
}

async function prepareBackend() {
  await ensureLocalEnv();
  await runCommand('npm', ['run', 'prisma:generate'], backendDir);
  await runCommand('npx', ['prisma', 'migrate', 'deploy'], backendDir);
  await runCommand('npm', ['run', 'prisma:seed'], backendDir);
}

function stopChildren() {
  for (const child of children) {
    if (!child.killed) {
      child.kill();
    }
  }
}

async function shutdown(exitCode = 0) {
  if (shuttingDown) {
    return;
  }

  shuttingDown = true;
  stopChildren();
  process.exit(exitCode);
}

async function main() {
  log('DEV', 'Smart Office Library launcher');

  if (checkOnly) {
    await ensureLocalEnv();
    const requiredFiles = [
      path.join(backendDir, 'package.json'),
      path.join(frontendDir, 'package.json'),
      path.join(backendDir, 'prisma', 'schema.prisma')
    ];

    for (const requiredFile of requiredFiles) {
      if (!(await pathExists(requiredFile))) {
        throw new Error(`Missing required file: ${path.relative(rootDir, requiredFile)}`);
      }
    }

    log('DEV', 'Configuration check passed');
    return;
  }

  await ensureDependencies();
  await prepareBackend();

  log('DEV', 'Starting backend, frontend, and Prisma Studio');
  log('DEV', 'Backend: http://localhost:4000');
  log('DEV', 'Frontend: http://localhost:5173');
  log('DEV', 'Prisma Studio: http://localhost:5555');

  spawnWithPrefix('BE', 'npm', ['run', 'dev'], backendDir);
  spawnWithPrefix('FE', 'npm', ['run', 'dev'], frontendDir);
  spawnWithPrefix('STUDIO', 'npm', ['run', 'prisma:studio'], backendDir);

  process.on('SIGINT', () => {
    void shutdown(0);
  });

  process.on('SIGTERM', () => {
    void shutdown(0);
  });

  await new Promise(() => {
    // Keep the launcher alive while the child processes run.
  });
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  void shutdown(1);
});