import { useMemo, useState } from 'react';
import axios from 'axios';
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  Fab,
  IconButton,
  Paper,
  Slide,
  Stack,
  TextField,
  Tooltip,
  Typography,
  useTheme,
  Chip
} from '@mui/material';
import ChatRoundedIcon from '@mui/icons-material/ChatRounded';
import CloseRoundedIcon from '@mui/icons-material/CloseRounded';
import SendRoundedIcon from '@mui/icons-material/SendRounded';
import SmartToyRoundedIcon from '@mui/icons-material/SmartToyRounded';
import AutoAwesomeIcon from '@mui/icons-material/AutoAwesome';
import { useAIChat, type AIMessage } from '../../hooks/useAI';
import { apiClient } from '../../api/axios';

type ChatMessage = AIMessage & {
  id: string;
  isRecommendation?: boolean;
};

const MAX_MESSAGES = 16;

const MOODS = [
  { label: '😊 Happy', value: 'happy', prompt: 'I am feeling happy and want uplifting, joyful books that will make me smile and brighten my day' },
  { label: '😢 Sad', value: 'sad', prompt: 'I am feeling sad and want emotionally deep, meaningful books that resonate with my feelings' },
  { label: '😴 Relaxed', value: 'relaxed', prompt: 'I am feeling relaxed and want easy-to-read, comforting books perfect for unwinding' },
  { label: '🚀 Adventurous', value: 'adventurous', prompt: 'I am feeling adventurous and want thrilling, action-packed books with exciting plots' },
  { label: '🤔 Thoughtful', value: 'thoughtful', prompt: 'I am feeling thoughtful and want intellectually stimulating, philosophical books to ponder' },
  { label: '👩‍💼 Motivated', value: 'motivated', prompt: 'I am feeling motivated and want inspirational, success-focused books to push my limits' }
];

const WELCOME_MESSAGE: ChatMessage = {
  id: 'welcome',
  role: 'assistant',
  content: 'Hi! I am your library assistant. Tell me your mood or ask for book suggestions, summaries, or reading help. 📚'
};

export const FloatingChatbot = () => {
  const theme = useTheme();
  const [open, setOpen] = useState(true); // Generated by GitHub Copilot - Auto-open on page load
  const [input, setInput] = useState('');
  const [chatError, setChatError] = useState<string | null>(null);
  const [messages, setMessages] = useState<ChatMessage[]>([WELCOME_MESSAGE]);
  const [loading, setLoading] = useState(false);
  const chatMutation = useAIChat();

  const historyForApi = useMemo(
    () => messages.filter((message) => message.id !== 'welcome' && !message.isRecommendation).map(({ role, content }) => ({ role, content })),
    [messages]
  );

  // Generated by GitHub Copilot
  // Database-backed mood recommendations - NO RATE LIMIT! 🎉
  const getMoodRecommendations = async (mood: string) => {
    try {
      setLoading(true);
      setChatError(null);

      // Call the database-backed endpoint instead of AI
      const response = await apiClient.post('/ai/mood-recommendations', {
        mood
      });

      const recommendations = response.data?.data?.recommendations;
      if (recommendations && Array.isArray(recommendations)) {
        let recommendationText = '📚 **Perfect books for your mood:**\n\n';

        recommendations.forEach((book: any, index: number) => {
          recommendationText += `${index + 1}. **${book.title}** by ${book.author}\n`;
          if (book.category) {
            recommendationText += `   📖 Category: ${book.category}\n`;
          }
          if (book.reason) {
            recommendationText += `   ✨ ${book.reason}\n`;
          }
          if (book.description) {
            recommendationText += `   📝 ${book.description.substring(0, 100)}...\n`;
          }
          recommendationText += '\n';
        });

        const assistantMessage: ChatMessage = {
          id: `assistant-${Date.now()}`,
          role: 'assistant',
          content: recommendationText,
          isRecommendation: true
        };
        setMessages((prev) => [...prev, assistantMessage].slice(-MAX_MESSAGES));
      }
    } catch (error: any) {
      // Silently handle database errors without showing rate limit message
      // This is a fallback, so just show generic "no books" message
      const fallbackMessage: ChatMessage = {
        id: `assistant-${Date.now()}`,
        role: 'assistant',
        content: 'Sorry, no books match your mood right now. Please try another mood or browse our catalog! 📚'
      };
      setMessages((prev) => [...prev, fallbackMessage].slice(-MAX_MESSAGES));
    } finally {
      setLoading(false);
    }
  };

  // Generated by GitHub Copilot
  const handleMoodClick = async (mood: typeof MOODS[0]) => {
    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: `I'm feeling ${mood.label}`
    };
    setMessages((prev) => [...prev, userMessage].slice(-MAX_MESSAGES));
    // Use database-backed mood recommendations (zero rate limit! 🎉)
    await getMoodRecommendations(mood.value);
  };

  // Generated by GitHub Copilot
  // Helper function to extract mood from user message
  const extractMood = (message: string): string | null => {
    const moodMatch = message.toLowerCase().match(/(happy|sad|relaxed|adventurous|thoughtful|motivated)/);
    return moodMatch ? moodMatch[1] : null;
  };

  const sendMessage = async () => {
    const trimmed = input.trim();
    if (!trimmed || chatMutation.isPending || loading) {
      return;
    }

    chatMutation.reset();
    setChatError(null);

    const userMessage: ChatMessage = {
      id: `user-${Date.now()}`,
      role: 'user',
      content: trimmed
    };

    const nextHistory: AIMessage[] = [...historyForApi, { role: userMessage.role, content: userMessage.content }];

    setMessages((prev) => [...prev, userMessage].slice(-MAX_MESSAGES));
    setInput('');

    try {
      // Always try AI chat first
      const responseText = await chatMutation.mutateAsync({ messages: nextHistory });
      const assistantMessage: ChatMessage = {
        id: `assistant-${Date.now()}`,
        role: 'assistant',
        content: String(responseText || 'I could not generate a response right now.')
      };
      setMessages((prev) => [...prev, assistantMessage].slice(-MAX_MESSAGES));
    } catch (error: any) {
      const status = axios.isAxiosError(error) ? error.response?.status : undefined;
      const isRateLimitError = status === 429;

      // If rate limited, automatically fallback to database mood recommendations
      if (isRateLimitError) {
        const detectedMood = extractMood(trimmed);
        if (detectedMood) {
          // Silently use database recommendations without showing rate limit error
          await getMoodRecommendations(detectedMood);
          return;
        }
      }

      // For other errors, show user-friendly message
      let alertMessage = 'Unable to reach the assistant right now. Please try again shortly.';
      if (status === 401) {
        alertMessage = 'Your session has expired. Please sign in again to use the chatbot.';
      }

      setChatError(alertMessage);

      const errorMessage: ChatMessage = {
        id: `assistant-error-${Date.now()}`,
        role: 'assistant',
        content: 'The assistant is temporarily unavailable. Try again in a moment or tell me your mood for book recommendations! 📚'
      };
      setMessages((prev) => [...prev, errorMessage].slice(-MAX_MESSAGES));
    }
  };

  const handleInputKeyDown = (event: React.KeyboardEvent<HTMLInputElement>) => {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      void sendMessage();
    }
  };

  return (
    <>
      <Slide direction='up' in={open}>
        <Paper
          elevation={16}
          sx={{
            position: 'fixed',
            right: { xs: 12, sm: 20 },
            bottom: { xs: 80, sm: 80 },
            width: { xs: 'calc(100vw - 24px)', sm: 340 },
            maxWidth: 340,
            height: { xs: '55vh', sm: 460 },
            zIndex: (muiTheme) => muiTheme.zIndex.modal + 2,
            borderRadius: 1.5,
            overflow: 'hidden',
            display: 'flex',
            flexDirection: 'column',
            border: '1px solid',
            borderColor: 'divider'
          }}
        >
          {/* Header */}
          <Box
            sx={{
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'space-between',
              px: 1.5,
              py: 1,
              minHeight: 44,
              background: theme.palette.mode === 'dark'
                ? 'linear-gradient(120deg, rgba(192,104,255,0.94) 0%, rgba(39,39,58,0.96) 100%)'
                : 'linear-gradient(120deg, rgba(161,0,255,0.96) 0%, rgba(127,29,255,0.94) 100%)',
              color: 'common.white',
              flexShrink: 0
            }}
          >
            <SmartToyRoundedIcon fontSize='small' />
            <Typography variant='subtitle2' sx={{ fontWeight: 700 }}>
              📚 Read Colab Assistant
            </Typography>
            <IconButton size='small' onClick={() => setOpen(false)} sx={{ color: 'common.white', p: 0.5 }}>
              <CloseRoundedIcon fontSize='small' />
            </IconButton>
          </Box>

          {/* Mood Quick Select */}
          <Box sx={{ px: 1, py: 0.75, borderBottom: '1px solid', borderColor: 'divider', bgcolor: 'background.paper', flexShrink: 0 }}>
            <Stack direction='row' sx={{ flexWrap: 'wrap', gap: 0.6, justifyContent: 'center' }}>
              {MOODS.map((mood) => (
                <Chip
                  key={mood.value}
                  label={mood.label}
                  onClick={() => handleMoodClick(mood)}
                  disabled={loading}
                  size='small'
                  variant='outlined'
                  sx={{ cursor: 'pointer', fontSize: '0.72rem', '&:hover': { borderColor: 'primary.main' } }}
                />
              ))}
            </Stack>
          </Box>

          <Box sx={{ p: 1.25, overflowY: 'auto', flex: 1, minHeight: 0, bgcolor: 'background.default' }}>
            <Stack spacing={1.1}>
              {messages.map((message) => {
                const fromUser = message.role === 'user';
                return (
                  <Box
                    key={message.id}
                    sx={{
                      alignSelf: fromUser ? 'flex-end' : 'flex-start',
                      maxWidth: '90%',
                      px: 1.2,
                      py: 0.9,
                      borderRadius: 1.5,
                      bgcolor: fromUser ? 'primary.main' : message.isRecommendation ? 'success.lighter' : 'background.paper',
                      color: fromUser ? 'primary.contrastText' : 'text.primary',
                      border: fromUser ? 'none' : '1px solid',
                      borderColor: fromUser ? 'transparent' : 'divider'
                    }}
                  >
                    <Typography variant='body2' sx={{ whiteSpace: 'pre-wrap' }}>
                      {message.content}
                    </Typography>
                  </Box>
                );
              })}
              {(chatMutation.isPending || loading) && (
                <Stack direction='row' spacing={1} alignItems='center' sx={{ pl: 0.5 }}>
                  <CircularProgress size={14} />
                  <Typography variant='caption' color='text.secondary'>
                    Getting personalized suggestions...
                  </Typography>
                </Stack>
              )}
            </Stack>
          </Box>

          <Box sx={{ p: 1.2, borderTop: '1px solid', borderColor: 'divider', bgcolor: 'background.paper', flexShrink: 0 }}>
            {chatError && (
              <Alert severity='warning' sx={{ mb: 1, fontSize: '0.85rem' }}>
                {chatError}
              </Alert>
            )}
            <Stack direction='row' spacing={1}>
              <TextField
                fullWidth
                size='small'
                placeholder='Or ask anything about books...'
                value={input}
                onChange={(event) => setInput(event.target.value)}
                onKeyDown={handleInputKeyDown}
                multiline
                maxRows={3}
                disabled={loading}
              />
              <IconButton
                color='primary'
                onClick={() => {
                  void sendMessage();
                }}
                disabled={!input.trim() || chatMutation.isPending || loading}
              >
                <SendRoundedIcon />
              </IconButton>
            </Stack>
          </Box>
        </Paper>
      </Slide>

      <Tooltip title='Chat with assistant' placement='left'>
        <Fab
          color='primary'
          aria-label='Open chatbot'
          onClick={() => setOpen((prev) => !prev)}
          sx={{
            position: 'fixed',
            right: { xs: 12, sm: 20 },
            bottom: { xs: 16, sm: 20 },
            zIndex: (muiTheme) => muiTheme.zIndex.modal + 3,
            boxShadow: theme.palette.mode === 'dark'
              ? '0 12px 28px rgba(192,104,255,0.42)'
              : '0 12px 28px rgba(161,0,255,0.36)',
            '&::after': {
              content: '""',
              position: 'absolute',
              inset: -7,
              borderRadius: '50%',
              border: theme.palette.mode === 'dark'
                ? '2px solid rgba(192,104,255,0.35)'
                : '2px solid rgba(161,0,255,0.28)',
              animation: 'chatPulse 1900ms ease-out infinite'
            },
            '@keyframes chatPulse': {
              '0%': { transform: 'scale(0.9)', opacity: 0.55 },
              '70%': { transform: 'scale(1.14)', opacity: 0 },
              '100%': { transform: 'scale(1.14)', opacity: 0 }
            }
          }}
        >
          <AutoAwesomeIcon />
        </Fab>
      </Tooltip>
    </>
  );
};
